"""Service for exporting Silos."""

from typing import Optional
from sqlalchemy.orm import Session
from models.silo import Silo
from schemas.export_schemas import (
    ExportSiloSchema,
    SiloExportFileSchema,
)
from services.base_export_service import BaseExportService
from services.embedding_service_export_service import EmbeddingServiceExportService
from services.output_parser_export_service import OutputParserExportService
from repositories.silo_repository import SiloRepository
import logging

logger = logging.getLogger(__name__)


class SiloExportService(BaseExportService):
    """Service for exporting Silos (vector store structure only)."""

    def __init__(self, session: Session):
        """Initialize Silo export service.

        Args:
            session: SQLAlchemy database session
        """
        super().__init__(session)
        self.silo_repo = SiloRepository()

    def export_silo(
        self,
        silo_id: int,
        app_id: int,
        user_id: Optional[int] = None,
        include_dependencies: bool = True,
    ) -> SiloExportFileSchema:
        """Export Silo to JSON structure.

        Note: Exports silo STRUCTURE only (no vector embeddings).
        Vector data must be regenerated by re-indexing documents after import.

        Args:
            silo_id: ID of silo to export
            app_id: App ID (for permission check)
            user_id: User ID (for permission check, optional)
            include_dependencies: If True, bundle embedding service and output
                parser in export file for portability

        Returns:
            SiloExportFileSchema: Export file structure

        Raises:
            ValueError: If silo not found or permission denied
        """
        # Load silo
        silo = self.silo_repo.get_by_id(silo_id, self.session)
        if not silo:
            raise ValueError(f"Silo with ID {silo_id} not found")

        # Permission check
        if silo.app_id != app_id:
            raise ValueError(
                f"Silo {silo_id} does not belong to app {app_id} "
                "(permission denied)"
            )

        # Get reference names
        embedding_service_name = None
        if silo.embedding_service:
            embedding_service_name = silo.embedding_service.name

        metadata_definition_name = None
        if silo.metadata_definition:
            metadata_definition_name = silo.metadata_definition.name

        # Create export schema (map silo_type -> type)
        export_silo = ExportSiloSchema(
            name=silo.name,
            type=silo.silo_type,  # DB field: silo_type
            vector_db_type=silo.vector_db_type or "UNKNOWN",  # Handle None
            embedding_service_name=embedding_service_name,
            metadata_definition_name=metadata_definition_name,
            fixed_metadata=silo.fixed_metadata,
            description=silo.description,
        )

        # Optionally bundle dependencies for portability
        bundled_embedding_service = None
        bundled_output_parser = None

        if include_dependencies:
            # Bundle embedding service
            if silo.embedding_service_id:
                try:
                    embedding_export_service = EmbeddingServiceExportService(
                        self.session
                    )
                    embedding_export_file = (
                        embedding_export_service.export_embedding_service(
                            silo.embedding_service_id, app_id, user_id
                        )
                    )
                    bundled_embedding_service = (
                        embedding_export_file.embedding_service
                    )
                    logger.info(
                        f"Bundled embedding service '{bundled_embedding_service.name}' "
                        f"in silo export"
                    )
                except Exception as e:
                    logger.warning(
                        f"Failed to bundle embedding service: {e}. "
                        f"Will export reference only."
                    )

            # Bundle output parser (metadata definition)
            if silo.metadata_definition_id:
                try:
                    parser_export_service = OutputParserExportService(self.session)
                    parser_export_file = parser_export_service.export_output_parser(
                        silo.metadata_definition_id, app_id, user_id
                    )
                    bundled_output_parser = parser_export_file.output_parser
                    logger.info(
                        f"Bundled output parser '{bundled_output_parser.name}' "
                        f"in silo export"
                    )
                except Exception as e:
                    logger.warning(
                        f"Failed to bundle output parser: {e}. "
                        f"Will export reference only."
                    )

        # Create export file
        export_file = SiloExportFileSchema(
            metadata=self.create_metadata(user_id, app_id),
            silo=export_silo,
            embedding_service=bundled_embedding_service,
            output_parser=bundled_output_parser,
        )

        logger.info(
            f"Exported Silo '{silo.name}' (ID: {silo_id}) - "
            f"Structure only, vectors excluded"
        )
        return export_file
