"""linked repos and silos

Revision ID: 06aaf1a6f0fe
Revises: ccbf913ffb46
Create Date: 2025-01-28 12:43:50.650187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06aaf1a6f0fe'
down_revision = 'ccbf913ffb46'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('Repository', sa.Column('silo_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'Repository', 'Silo', ['silo_id'], ['silo_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Repository', type_='foreignkey')
    op.drop_column('Repository', 'silo_id')
    
    # ### end Alembic commands ###
