"""add marketplace usage tracking table

Revision ID: 08001655fb7e
Revises: 5335c57f74cd
Create Date: 2026-03-09 17:36:56.987229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08001655fb7e'
down_revision = '5335c57f74cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MarketplaceUsage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_user_year_month')
    )
    op.create_index('ix_user_id', 'MarketplaceUsage', ['user_id'], unique=False)
    op.create_index('ix_user_year_month', 'MarketplaceUsage', ['user_id', 'year', 'month'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_year_month', table_name='MarketplaceUsage')
    op.drop_index('ix_user_id', table_name='MarketplaceUsage')
    op.drop_table('MarketplaceUsage')
    # ### end Alembic commands ###
