"""bind ai and embedding services to apps

Revision ID: 0c9bd45273ec
Revises: 7e27609b5faf
Create Date: 2025-03-24 09:58:45.944466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c9bd45273ec'
down_revision = '7e27609b5faf'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('AIService', sa.Column('app_id', sa.Integer(), nullable=False))
    op.alter_column('AIService', 'provider',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.create_foreign_key(None, 'AIService', 'App', ['app_id'], ['app_id'])
    op.add_column('embedding_service', sa.Column('app_id', sa.Integer(), nullable=False))
    op.alter_column('embedding_service', 'provider',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.create_foreign_key(None, 'embedding_service', 'App', ['app_id'], ['app_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embedding_service', type_='foreignkey')
    op.alter_column('embedding_service', 'provider',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.drop_column('embedding_service', 'app_id')
    op.drop_constraint(None, 'AIService', type_='foreignkey')
    op.alter_column('AIService', 'provider',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.drop_column('AIService', 'app_id')
