"""Added login and register with email and password

Revision ID: 1cd057577c6e
Revises: 9c15471c92fe
Create Date: 2025-08-04 10:27:31.561891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd057577c6e'
down_revision = '9c15471c92fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AIService', 'vast_token')
    op.add_column('User', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('User', sa.Column('is_google_user', sa.Boolean(), nullable=True))
    op.drop_column('embedding_service', 'vast_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_service', sa.Column('vast_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('User', 'is_google_user')
    op.drop_column('User', 'password_hash')
    op.add_column('AIService', sa.Column('vast_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
