"""Add Media and MediaChunk tables

Revision ID: 338def34f339
Revises: d9c43f453f24
Create Date: 2026-01-13 12:14:34.725465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338def34f339'
down_revision = 'd9c43f453f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Media',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=45), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['Folder.folder_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['Repository.repository_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('MediaChunk',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['Media.media_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MediaChunk')
    op.drop_table('Media')
    # ### end Alembic commands ###
