"""Added MistralEmbeddings

Revision ID: 372d11cf29a7
Revises: e37008978da7
Create Date: 2025-04-09 23:39:47.150304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372d11cf29a7'
down_revision = 'e37008978da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
