"""simplify_mcp_config_structure

Revision ID: 3d568387b418
Revises: 8fe20813a159
Create Date: 2025-10-04 20:26:24.169779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d568387b418'
down_revision = '8fe20813a159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add config column with default empty JSON object to handle existing rows
    op.add_column('MCPConfig', sa.Column('config', sa.JSON(), nullable=False, server_default='{}'))
    
    op.alter_column('MCPConfig', 'name',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('MCPConfig', 'encoding_error_handler')
    op.drop_column('MCPConfig', 'url')
    op.drop_column('MCPConfig', 'inputs')
    op.drop_column('MCPConfig', 'timeout')
    op.drop_column('MCPConfig', 'encoding')
    op.drop_column('MCPConfig', 'server_name')
    op.drop_column('MCPConfig', 'headers')
    op.drop_column('MCPConfig', 'args')
    op.drop_column('MCPConfig', 'command')
    op.drop_column('MCPConfig', 'env')
    op.drop_column('MCPConfig', 'transport_type')
    op.drop_column('MCPConfig', 'sse_read_timeout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MCPConfig', sa.Column('sse_read_timeout', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('transport_type', postgresql.ENUM('STDIO', 'SSE', name='transporttype'), autoincrement=False, nullable=False))
    op.add_column('MCPConfig', sa.Column('env', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('command', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('server_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.add_column('MCPConfig', sa.Column('encoding', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('timeout', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('inputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('MCPConfig', sa.Column('encoding_error_handler', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('MCPConfig', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
    op.drop_column('MCPConfig', 'config')
    # ### end Alembic commands ###
