"""Delete Media Chunk table

Revision ID: 3e9d370bd29b
Revises: 651adc60ad22
Create Date: 2026-01-29 12:05:33.521395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e9d370bd29b'
down_revision = '651adc60ad22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MediaChunk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MediaChunk',
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['Media.media_id'], name=op.f('MediaChunk_media_id_fkey')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('MediaChunk_pkey'))
    )
    # ### end Alembic commands ###
