"""remove_subscription_tables

Revision ID: 42c2b73b86da
Revises: df20392c6cbe
Create Date: 2025-11-11 11:36:29.503812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42c2b73b86da'
down_revision = 'srotilms3ht3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop subscription-related tables
    op.drop_index(op.f('idx_subscription_year_month'), table_name='APIUsage')
    op.drop_index(op.f('idx_user_year_month'), table_name='APIUsage')
    op.drop_table('APIUsage')
    op.drop_table('Subscription')
    op.drop_table('Plan')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Subscription tables are legacy and should not be recreated
    # Recreating tables for downgrade compatibility only
    op.create_table('Subscription',
    sa.Column('subscription_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Subscription_subscription_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'CANCELLED', 'EXPIRED', 'TRIAL', name='subscriptionstatus'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_trial', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('trial_ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_payment_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_payment_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['Plan.plan_id'], name='Subscription_plan_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='Subscription_user_id_fkey'),
    sa.PrimaryKeyConstraint('subscription_id', name='Subscription_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Plan',
    sa.Column('plan_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Plan_plan_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('billing_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('max_agents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_storage_gb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_domains', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_api_calls_per_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_priority_support', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_advanced_analytics', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_team_collaboration', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_custom_integrations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_on_premise', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('plan_id', name='Plan_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('APIUsage',
    sa.Column('usage_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_calls_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['Subscription.subscription_id'], name=op.f('APIUsage_subscription_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name=op.f('APIUsage_user_id_fkey')),
    sa.PrimaryKeyConstraint('usage_id', name=op.f('APIUsage_pkey'))
    )
    op.create_index(op.f('idx_user_year_month'), 'APIUsage', ['user_id', 'year', 'month'], unique=False)
    op.create_index(op.f('idx_subscription_year_month'), 'APIUsage', ['subscription_id', 'year', 'month'], unique=False)
    # ### end Alembic commands ###
