"""Added langsmith to app

Revision ID: 483826553cd5
Revises: 372d11cf29a7
Create Date: 2025-04-25 09:13:05.605190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483826553cd5'
down_revision = '76f37ab0ce9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('App', sa.Column('langsmith_api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('App', 'langsmith_api_key')
    # ### end Alembic commands ###
