"""IA Core Tools 2

Revision ID: 489c8afcff5b
Revises: b3a5f986d5d7
Create Date: 2024-10-08 12:27:57.814681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489c8afcff5b'
down_revision = 'b3a5f986d5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Model',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=45), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Repository',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.create_table('Agent',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('has_memory', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['Model.model_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['Repository.repository_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('Resource',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('uri', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['Repository.repository_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resource')
    op.drop_table('Agent')
    op.drop_table('Repository')
    op.drop_table('User')
    op.drop_table('Model')
    # ### end Alembic commands ###
