"""Domains and urls

Revision ID: 48aea27275aa
Revises: 84c0512e901d
Create Date: 2025-02-07 14:24:58.913009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48aea27275aa'
down_revision = '84c0512e901d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Domain',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('content_tag', sa.String(length=255), nullable=True),
    sa.Column('content_class', sa.String(length=255), nullable=True),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('silo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.ForeignKeyConstraint(['silo_id'], ['Silo.silo_id'], ),
    sa.PrimaryKeyConstraint('domain_id')
    )
    op.create_table('Url',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['Domain.domain_id'], ),
    sa.PrimaryKeyConstraint('url_id')
    )
    


def downgrade():
    
    op.drop_table('Url')
    op.drop_table('Domain')
    # ### end Alembic commands ###
