"""add_folder_table_and_resource_folder_id

Revision ID: 4b456a21f90b
Revises: 3d568387b418
Create Date: 2025-10-12 00:37:56.919820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b456a21f90b'
down_revision = '3d568387b418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Folder',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['Folder.folder_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['Repository.repository_id'], ),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.add_column('Resource', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Resource', 'Folder', ['folder_id'], ['folder_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Resource', type_='foreignkey')
    op.drop_column('Resource', 'folder_id')
    op.drop_table('Folder')
    # ### end Alembic commands ###
