"""Created MCP Config entity

Revision ID: 4efb28492fea
Revises: f46af6004ad2
Create Date: 2025-03-28 11:45:21.215676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efb28492fea'
down_revision = 'f46af6004ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MCPConfig',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('transport_type', sa.Enum('STDIO', 'SSE', name='transporttype'), nullable=False),
    sa.Column('server_name', sa.String(length=45), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('command', sa.String(length=255), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('env', sa.JSON(), nullable=True),
    sa.Column('encoding', sa.String(length=10), nullable=True),
    sa.Column('encoding_error_handler', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('sse_read_timeout', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MCPConfig')
    # ### end Alembic commands ###
