"""Added agent_rate_limit to app model

Revision ID: 5706422a57c2
Revises: 9c15471c92fe
Create Date: 2025-09-29 17:13:19.379935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5706422a57c2'
down_revision = '9c15471c92fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('App', sa.Column('agent_rate_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('App', 'agent_rate_limit')
    # ### end Alembic commands ###
