"""added type to silo

Revision ID: 5cc4c107ece8
Revises: 06aaf1a6f0fe
Create Date: 2025-02-04 18:12:01.666201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cc4c107ece8'
down_revision = '06aaf1a6f0fe'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('Silo', sa.Column('silo_type', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Silo', 'silo_type')
    
