"""Embedding services relations with repos and silos added

Revision ID: 5d392cc2e23f
Revises: a15a253570b8
Create Date: 2025-03-21 10:35:11.521375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d392cc2e23f'
down_revision = 'a15a253570b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Silo', sa.Column('embedding_service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Silo', 'embedding_service', ['embedding_service_id'], ['service_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Silo', type_='foreignkey')
    op.drop_column('Silo', 'embedding_service_id')
    # ### end Alembic commands ###
