"""Add ai_service_id column to media table

Revision ID: 651adc60ad22
Revises: 338def34f339
Create Date: 2026-01-26 13:32:36.002980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651adc60ad22'
down_revision = '338def34f339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Media', sa.Column('transcription_service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Media', 'AIService', ['transcription_service_id'], ['service_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Media', type_='foreignkey')
    op.drop_column('Media', 'transcription_service_id')
    # ### end Alembic commands ###
