"""Add max_file_size_mb to App model

Revision ID: 7001831172b8
Revises: 4b456a21f90b
Create Date: 2025-10-14 13:12:39.197989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7001831172b8'
down_revision = '4b456a21f90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('App', sa.Column('max_file_size_mb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('App', 'max_file_size_mb')
    # ### end Alembic commands ###
