"""1 to n relation agent to mcps

Revision ID: 76f37ab0ce9e
Revises: 372d11cf29a7
Create Date: 2025-04-24 16:35:08.277988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f37ab0ce9e'
down_revision = '372d11cf29a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_mcps',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['Agent.agent_id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['MCPConfig.config_id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'config_id')
    )
    op.drop_constraint('Agent_mcp_config_id_fkey', 'Agent', type_='foreignkey')
    op.drop_column('Agent', 'mcp_config_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agent', sa.Column('mcp_config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Agent_mcp_config_id_fkey', 'Agent', 'MCPConfig', ['mcp_config_id'], ['config_id'])
    op.drop_table('agent_mcps')
    # ### end Alembic commands ###
