"""correct provider attr

Revision ID: 7e27609b5faf
Revises: 5d392cc2e23f
Create Date: 2025-03-21 16:42:53.851074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e27609b5faf'
down_revision = '5d392cc2e23f'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('AIService', sa.Column('provider', sa.String(length=45), nullable=False))
    op.drop_constraint('Agent_service_id_fkey', 'Agent', type_='foreignkey')
    op.create_foreign_key(None, 'Agent', 'AIService', ['service_id'], ['service_id'], ondelete='SET NULL')
    op.add_column('embedding_service', sa.Column('provider', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_service', 'provider')
    op.drop_constraint(None, 'Agent', type_='foreignkey')
    op.create_foreign_key('Agent_service_id_fkey', 'Agent', 'AIService', ['service_id'], ['service_id'])
    op.drop_column('AIService', 'provider')
    
