"""add_subscription_models_proper

Revision ID: 7ec8cfef5243
Revises: 9878217d10f4
Create Date: 2025-06-08 20:08:14.900563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec8cfef5243'
down_revision = '9878217d10f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Plan',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Integer(), nullable=True),
    sa.Column('max_domains', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('has_priority_support', sa.Boolean(), nullable=True),
    sa.Column('has_advanced_analytics', sa.Boolean(), nullable=True),
    sa.Column('has_team_collaboration', sa.Boolean(), nullable=True),
    sa.Column('has_custom_integrations', sa.Boolean(), nullable=True),
    sa.Column('has_on_premise', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('Subscription',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', 'TRIAL', name='subscriptionstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(), nullable=True),
    sa.Column('next_payment_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['Plan.plan_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subscription')
    op.drop_table('Plan')
    # ### end Alembic commands ###
