"""Binding agent to silo instead of repo

Revision ID: 7fa5273b160e
Revises: 5cc4c107ece8
Create Date: 2025-02-05 14:39:55.950778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fa5273b160e'
down_revision = '5cc4c107ece8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agent', sa.Column('silo_id', sa.Integer(), nullable=True))
    op.drop_constraint('Agent_repository_id_fkey', 'Agent', type_='foreignkey')
    op.create_foreign_key(None, 'Agent', 'Silo', ['silo_id'], ['silo_id'])
    op.drop_column('Agent', 'repository_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agent', sa.Column('repository_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Agent', type_='foreignkey')
    op.create_foreign_key('Agent_repository_id_fkey', 'Agent', 'Repository', ['repository_id'], ['repository_id'])
    op.drop_column('Agent', 'silo_id')
    # ### end Alembic commands ###
