"""Added request count to agents

Revision ID: 84c0512e901d
Revises: 06aaf1a6f0fe
Create Date: 2025-01-31 16:42:50.871715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84c0512e901d'
down_revision = '7fa5273b160e'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('Agent', sa.Column('request_count', sa.Integer(), nullable=True))
    op.add_column('OCRAgent', sa.Column('request_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OCRAgent', 'request_count')
    op.drop_column('Agent', 'request_count')