"""Add unique constraint on resource repo_folder_uri

Revision ID: 84e218bbc5c5
Revises: a35f5996ece4
Create Date: 2026-02-06 13:46:42.460078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e218bbc5c5'
down_revision = 'a35f5996ece4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_resource_repo_folder_uri', 'Resource', ['repository_id', 'folder_id', 'uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_resource_repo_folder_uri', 'Resource', type_='unique')
    # ### end Alembic commands ###
