"""merging agents

Revision ID: 85ae9de23cef
Revises: 84c0512e901d
Create Date: 2025-02-08 06:55:56.363137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85ae9de23cef'
down_revision = '84c0512e901d'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint('OCRAgent_model_id_fkey', 'OCRAgent', type_='foreignkey')
    op.drop_constraint('OCRAgent_app_id_fkey', 'OCRAgent', type_='foreignkey')
    op.drop_constraint('OCRAgent_output_parser_id_fkey', 'OCRAgent', type_='foreignkey')
    op.create_foreign_key(None, 'OCRAgent', 'Agent', ['agent_id'], ['agent_id'])
    op.drop_column('OCRAgent', 'model_id')
    op.drop_column('OCRAgent', 'output_parser_id')
    op.drop_column('OCRAgent', 'description')
    op.drop_column('OCRAgent', 'request_count')
    op.drop_column('OCRAgent', 'name')
    op.drop_column('OCRAgent', 'app_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OCRAgent', sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('OCRAgent', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('OCRAgent', sa.Column('request_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('OCRAgent', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('OCRAgent', sa.Column('output_parser_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('OCRAgent', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'OCRAgent', type_='foreignkey')
    op.create_foreign_key('OCRAgent_output_parser_id_fkey', 'OCRAgent', 'OutputParser', ['output_parser_id'], ['parser_id'])
    op.create_foreign_key('OCRAgent_app_id_fkey', 'OCRAgent', 'App', ['app_id'], ['app_id'])
    op.create_foreign_key('OCRAgent_model_id_fkey', 'OCRAgent', 'Model', ['model_id'], ['model_id'])
