"""add_temperature_to_agent

Revision ID: 8fe20813a159
Revises: 5706422a57c2
Create Date: 2025-10-01 12:44:30.873964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe20813a159'
down_revision = '5706422a57c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agent', sa.Column('temperature', sa.Float(), nullable=False, server_default='0.7'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Agent', 'temperature')
    # ### end Alembic commands ###
