"""Descriptions for agent tool relationship

Revision ID: 986475e9f1f5
Revises: 48aea27275aa
Create Date: 2025-02-21 16:03:11.955951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '986475e9f1f5'
down_revision = '48aea27275aa'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('Url', 'domain_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('agent_tools', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tools', 'description')
    op.alter_column('Url', 'domain_id',
               existing_type=sa.INTEGER(),
               nullable=True)

