"""agents with tools and toolable agents

Revision ID: 986e6729e99d
Revises: 85ae9de23cef
Create Date: 2025-02-13 12:30:30.679342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '986e6729e99d'
down_revision = '85ae9de23cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['Agent.agent_id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['Agent.agent_id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )

    op.add_column('Agent', sa.Column('is_tool', sa.Boolean(), nullable=True))
    op.alter_column('Agent', 'type',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Agent', 'type',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.drop_column('Agent', 'is_tool')
    op.drop_table('agent_tools')
    # ### end Alembic commands ###
