"""add_subscription_models

Revision ID: 9878217d10f4
Revises: e46a4d969e27
Create Date: 2025-06-08 20:07:00.668079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9878217d10f4'
down_revision = 'e46a4d969e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Agent_mcp_config_id_fkey', 'Agent', type_='foreignkey')
    op.drop_column('Agent', 'mcp_config_id')
    op.alter_column('MCPConfig', 'inputs',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='inputs::json')
    op.alter_column('agent_mcps', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_mcps', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('MCPConfig', 'inputs',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('Agent', sa.Column('mcp_config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Agent_mcp_config_id_fkey', 'Agent', 'MCPConfig', ['mcp_config_id'], ['config_id'])
    # ### end Alembic commands ###
