"""add_app_collaborations

Revision ID: 9c15471c92fe
Revises: db8662e5c1b5
Create Date: 2025-06-26 14:58:22.723162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c15471c92fe'
down_revision = 'db8662e5c1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppCollaborator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', name='collaborationrole'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='collaborationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('App', sa.Column('owner_id', sa.Integer(), nullable=True))
    
    # Data migration: copy user_id to owner_id
    op.execute("UPDATE \"App\" SET owner_id = user_id WHERE user_id IS NOT NULL")
    
    op.drop_constraint('App_user_id_fkey', 'App', type_='foreignkey')
    op.create_foreign_key(None, 'App', 'User', ['owner_id'], ['user_id'])
    op.drop_column('App', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('App', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Data migration: copy owner_id back to user_id
    op.execute("UPDATE \"App\" SET user_id = owner_id WHERE owner_id IS NOT NULL")
    
    op.drop_constraint(None, 'App', type_='foreignkey')
    op.create_foreign_key('App_user_id_fkey', 'App', 'User', ['user_id'], ['user_id'])
    op.drop_column('App', 'owner_id')
    op.drop_table('AppCollaborator')
    # ### end Alembic commands ###
