"""add_server_tools_to_agent

Revision ID: 9febd6c0d636
Revises: fd246f03e470
Create Date: 2026-02-27 23:12:58.076198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9febd6c0d636'
down_revision = 'fd246f03e470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agent', sa.Column('server_tools', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Agent', 'server_tools')
    # ### end Alembic commands ###
