"""Embedding services added

Revision ID: a15a253570b8
Revises: edc20b9a73de
Create Date: 2025-03-21 10:09:28.304784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a15a253570b8'
down_revision = 'edc20b9a73de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_embedding_service_service_id'), 'embedding_service', ['service_id'], unique=False)
    op.drop_column('AIService', 'provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIService', sa.Column('provider', postgresql.ENUM('OpenAI', 'Anthropic', 'MistralAI', 'Custom', name='providerenum'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_embedding_service_service_id'), table_name='embedding_service')
    op.drop_table('embedding_service')
    # ### end Alembic commands ###
