"""add_viewer_role_to_collaboration

Revision ID: a35f5996ece4
Revises: 2523d3e13423
Create Date: 2025-11-25 09:26:08.370300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a35f5996ece4'
down_revision = '2523d3e13423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE collaborationrole ADD VALUE IF NOT EXISTS 'VIEWER'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
