"""add Antrophic models

Revision ID: a6d7ddf5f9ed
Revises: a460ad150e9e
Create Date: 2024-10-09 11:27:44.540056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d7ddf5f9ed'
down_revision = 'a460ad150e9e'
branch_labels = None
depends_on = None


def upgrade():
    op.bulk_insert(
        sa.table('Model',
            sa.column('provider', sa.String),
            sa.column('name', sa.String),
            sa.column('description', sa.String)
        ),
        [
            {'provider': 'Anthropic', 'name': 'claude-3-5-sonnet-20240620', 'description': 'Most intelligent model. Highest level of intelligence and capability. 200k token context window.'},
            {'provider': 'Anthropic', 'name': 'claude-3-opus-20240229', 'description': 'Powerful model for highly complex tasks. Top-level performance, intelligence, fluency, and understanding'}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
