"""hf_ai_service

Revision ID: adc97721b82c
Revises: 9c15471c92fe
Create Date: 2025-07-07 10:56:25.841543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc97721b82c'
down_revision = '9c15471c92fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Añadir nuevos valores al enum providerenum
    op.execute("ALTER TYPE providerenum ADD VALUE 'Azure'")
    op.execute("ALTER TYPE providerenum ADD VALUE 'HuggingFace'")
    
    # Cambiar 'Custom' por 'Ollama' en registros existentes
    op.execute("UPDATE \"AIService\" SET provider = 'Ollama' WHERE provider = 'Custom'")
    
    # Añadir el nuevo valor 'Ollama' al enum después de actualizar los registros
    op.execute("ALTER TYPE providerenum ADD VALUE 'Ollama'")
    
    # Añadir columnas vast_token
    op.add_column('AIService', sa.Column('vast_token', sa.String(length=255), nullable=True))
    op.add_column('embedding_service', sa.Column('vast_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar columnas vast_token
    op.drop_column('embedding_service', 'vast_token')
    op.drop_column('AIService', 'vast_token')
    
    # Revertir 'Ollama' a 'Custom' en registros existentes
    op.execute("UPDATE \"AIService\" SET provider = 'Custom' WHERE provider = 'Ollama'")
    
    # Nota: PostgreSQL no permite eliminar valores de enum fácilmente
    # Los valores 'Azure', 'HuggingFace' y 'Ollama' permanecerán en el enum
    # ### end Alembic commands ###
