"""Add APIUsage table for subscription-level API tracking

Revision ID: b3b8b98fbcf2
Revises: 7ec8cfef5243
Create Date: 2025-06-08 20:29:33.285479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b8b98fbcf2'
down_revision = '7ec8cfef5243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APIUsage',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('api_calls_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['Subscription.subscription_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('idx_subscription_year_month', 'APIUsage', ['subscription_id', 'year', 'month'], unique=False)
    op.create_index('idx_user_year_month', 'APIUsage', ['user_id', 'year', 'month'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_year_month', table_name='APIUsage')
    op.drop_index('idx_subscription_year_month', table_name='APIUsage')
    op.drop_table('APIUsage')
    # ### end Alembic commands ###
