"""Added agent_cors_origins

Revision ID: c087a095bdd2
Revises: 5706422a57c2
Create Date: 2025-10-01 12:26:59.604763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c087a095bdd2'
down_revision = '5706422a57c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('App', sa.Column('agent_cors_origins', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('App', 'agent_cors_origins')
    # ### end Alembic commands ###
