"""Silos added

Revision ID: ccbf913ffb46
Revises: 59e8d529b38a
Create Date: 2025-01-19 15:16:49.470781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbf913ffb46'
down_revision = '59e8d529b38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Silo',
    sa.Column('silo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('fixed_metadata', sa.Boolean(), nullable=True),
    sa.Column('metadata_definition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.ForeignKeyConstraint(['metadata_definition_id'], ['OutputParser.parser_id'], ),
    sa.PrimaryKeyConstraint('silo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Silo')
    # ### end Alembic commands ###
