"""Add Media and MediaChunk tables

Revision ID: d9c43f453f24
Revises: a35f5996ece4
Create Date: 2026-01-13 12:06:28.299823

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd9c43f453f24'
down_revision = 'a35f5996ece4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversation_agent_api'), table_name='Conversation')
    op.drop_index(op.f('idx_conversation_agent_user'), table_name='Conversation')
    op.drop_index(op.f('idx_conversation_updated_at'), table_name='Conversation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_conversation_updated_at'), 'Conversation', ['updated_at'], unique=False)
    op.create_index(op.f('idx_conversation_agent_user'), 'Conversation', ['agent_id', 'user_id'], unique=False)
    op.create_index(op.f('idx_conversation_agent_api'), 'Conversation', ['agent_id', 'api_key_hash'], unique=False)
    # ### end Alembic commands ###
