"""Añadido azure chat models

Revision ID: db8662e5c1b5
Revises: b3b8b98fbcf2
Create Date: 2025-06-24 09:13:47.146934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8662e5c1b5'
down_revision = 'b3b8b98fbcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIService', sa.Column('api_version', sa.String(length=50), nullable=True))
    op.add_column('embedding_service', sa.Column('api_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_service', 'api_version')
    op.drop_column('AIService', 'api_version')
    # ### end Alembic commands ###
