"""DB base 1

Revision ID: df947a43f4ba
Revises: 
Create Date: 2024-12-29 20:44:43.606394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df947a43f4ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Model',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=45), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('App',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('APIKey',
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('OutputParser',
    sa.Column('parser_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.PrimaryKeyConstraint('parser_id')
    )
    op.create_table('Repository',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.create_table('Agent',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('has_memory', sa.Boolean(), nullable=True),
    sa.Column('output_parser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['Model.model_id'], ),
    sa.ForeignKeyConstraint(['output_parser_id'], ['OutputParser.parser_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['Repository.repository_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('OCRAgent',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('vision_model_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('vision_system_prompt', sa.Text(), nullable=True),
    sa.Column('text_system_prompt', sa.Text(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('output_parser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['Model.model_id'], ),
    sa.ForeignKeyConstraint(['output_parser_id'], ['OutputParser.parser_id'], ),
    sa.ForeignKeyConstraint(['vision_model_id'], ['Model.model_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('Resource',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('uri', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['Repository.repository_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resource')
    op.drop_table('OCRAgent')
    op.drop_table('Agent')
    op.drop_table('Repository')
    op.drop_table('OutputParser')
    op.drop_table('APIKey')
    op.drop_table('App')
    op.drop_table('User')
    op.drop_table('Model')
    # ### end Alembic commands ###
