"""Agents may refer an MCP

Revision ID: e37008978da7
Revises: 4efb28492fea
Create Date: 2025-03-28 15:22:59.403814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37008978da7'
down_revision = '4efb28492fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agent', sa.Column('mcp_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Agent', 'MCPConfig', ['mcp_config_id'], ['config_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Agent', type_='foreignkey')
    op.drop_column('Agent', 'mcp_config_id')
    # ### end Alembic commands ###
