"""Added inputs field to mcp config

Revision ID: e46a4d969e27
Revises: 483826553cd5
Create Date: 2025-04-29 12:03:26.833182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46a4d969e27'
down_revision = '483826553cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MCPConfig', sa.Column('inputs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MCPConfig', 'inputs')
    # ### end Alembic commands ###
