"""Added update model to AIService

Revision ID: edc20b9a73de
Revises: 986475e9f1f5
Create Date: 2025-02-27 11:34:40.628511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc20b9a73de'
down_revision = '986475e9f1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AIService',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('OpenAI', 'Anthropic', 'MistralAI', 'Custom', name='providerenum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_AIService_service_id'), 'AIService', ['service_id'], unique=False)
    op.drop_constraint('Agent_model_id_fkey', 'Agent', type_='foreignkey')
    op.drop_constraint('OCRAgent_vision_model_id_fkey', 'OCRAgent', type_='foreignkey')
    op.drop_table('Model')
    op.add_column('Agent', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Agent', 'AIService', ['service_id'], ['service_id'])
    op.drop_column('Agent', 'model_id')
    op.add_column('OCRAgent', sa.Column('vision_service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'OCRAgent', 'AIService', ['vision_service_id'], ['service_id'])
    op.drop_column('OCRAgent', 'vision_model_id')
    op.alter_column('Url', 'domain_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Url', 'domain_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('OCRAgent', sa.Column('vision_model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'OCRAgent', type_='foreignkey')
    op.create_foreign_key('OCRAgent_vision_model_id_fkey', 'OCRAgent', 'Model', ['vision_model_id'], ['model_id'])
    op.drop_column('OCRAgent', 'vision_service_id')
    op.add_column('Agent', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Agent', type_='foreignkey')
    op.create_foreign_key('Agent_model_id_fkey', 'Agent', 'Model', ['model_id'], ['model_id'])
    op.drop_column('Agent', 'service_id')
    op.create_table('Model',
    sa.Column('model_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('model_id', name='Model_pkey')
    )
    op.drop_index(op.f('ix_AIService_service_id'), table_name='AIService')
    op.drop_table('AIService')
    # ### end Alembic commands ###