"""add_ocr_and_output_parser_tables

Revision ID: f0491b303a20
Revises: a6d7ddf5f9ed
Create Date: 2024-12-05 11:52:03.839010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0491b303a20'
down_revision = 'a6d7ddf5f9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OutputParser',
    sa.Column('parser_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.PrimaryKeyConstraint('parser_id')
    )
    op.create_table('OCRAgent',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('vision_model_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('vision_system_prompt', sa.Text(), nullable=True),
    sa.Column('text_system_prompt', sa.Text(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('output_parser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['App.app_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['Model.model_id'], ),
    sa.ForeignKeyConstraint(['output_parser_id'], ['OutputParser.parser_id'], ),
    sa.ForeignKeyConstraint(['vision_model_id'], ['Model.model_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.add_column('Agent', sa.Column('output_parser_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Agent', 'OutputParser', ['output_parser_id'], ['parser_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Agent', type_='foreignkey')
    op.drop_column('Agent', 'output_parser_id')
    op.drop_table('OCRAgent')
    op.drop_table('OutputParser')
    # ### end Alembic commands ###
