"""Added create_date attr

Revision ID: f46af6004ad2
Revises: 0c9bd45273ec
Create Date: 2025-03-25 11:25:29.770616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46af6004ad2'
down_revision = '0c9bd45273ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIService', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('App', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('Domain', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('OutputParser', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('Repository', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('Silo', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('embedding_service', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('Agent', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('Resource', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resource', 'create_date')
    op.drop_column('Agent', 'create_date')
    op.drop_column('embedding_service', 'create_date')
    op.drop_column('User', 'create_date')
    op.drop_column('Silo', 'create_date')
    op.drop_column('Repository', 'create_date')
    op.drop_column('OutputParser', 'create_date')
    op.drop_column('Domain', 'create_date')
    op.drop_column('App', 'create_date')
    op.drop_column('AIService', 'create_date')
    # ### end Alembic commands ###
