"""Add enable_code_interpreter to Agent

Revision ID: fd246f03e470
Revises: cb4e00ec0e72
Create Date: 2026-02-27 16:35:47.288042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd246f03e470'
down_revision = 'cb4e00ec0e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agent', sa.Column('enable_code_interpreter', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_app_slug'), table_name='App')
    op.create_unique_constraint(None, 'App', ['slug'])
    op.alter_column('MCPServer', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('MCPServer', 'rate_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MCPServer', 'rate_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('MCPServer', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'App', type_='unique')
    op.create_index(op.f('ix_app_slug'), 'App', ['slug'], unique=True)
    op.drop_column('Agent', 'enable_code_interpreter')
    # ### end Alembic commands ###
