"""added type to silo

Revision ID: 4641a61506b4
Revises: 06aaf1a6f0fe
Create Date: 2025-02-04 17:49:18.248881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4641a61506b4'
down_revision = '06aaf1a6f0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Silo', sa.Column('silo_type', sa.Enum('CUSTOM', 'REPO', 'CRAWLER', name='silo_type_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Silo', 'silo_type')
    
    # ### end Alembic commands ###
