"""Golden SSE regression tests for ``AgentStreamingService.stream_agent_chat``.

These tests pin the **exact, byte-for-byte** ``format_sse_event`` strings that
``stream_agent_chat`` yields today, before the AD-5 streaming-seam refactor
(step_008) splits it into ``stream_agent_events`` + a thin SSE bridge. They
must keep passing, unmodified, after that refactor (plan step_008 task #7).

Per the plan (step_004): the expected strings below were generated by running
the **current**, unrefactored code once and freezing the output as literals —
they are not recomputed via ``format_sse_event`` in the assertions, so a
accidental change to event ordering, key ordering or payload shape is caught.

No DB is used — everything ``stream_agent_chat`` would normally fetch via
``AgentExecutionService`` is monkeypatched at the ``services.agent_streaming_service``
import site.
"""
from __future__ import annotations

import asyncio
from types import SimpleNamespace
from unittest.mock import AsyncMock, MagicMock, patch

import psycopg.errors
import pytest
from langchain_core.messages import AIMessage, AIMessageChunk, ToolMessage


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _make_ctx(
    *,
    has_memory: bool = False,
    conversation=None,
    session_id_for_cache=None,
):
    """Build the fake ``AgentExecutionContext`` the real _prepare_turn() would
    return, with only the attributes ``stream_agent_chat`` actually reads."""
    fresh_agent = SimpleNamespace(agent_id=1, has_memory=has_memory, app=None)
    agent = SimpleNamespace(name="TestAgent", has_memory=has_memory)
    return SimpleNamespace(
        agent_id=1,
        agent=agent,
        fresh_agent=fresh_agent,
        effective_conv_id=297,
        conversation=conversation,
        session_id_for_cache=session_id_for_cache,
        user_context={"user_id": "u1"},
        image_files=[],
        processed_files=[],
        enhanced_message="hello",
        search_params={},
        working_dir="/tmp/work",
        sandbox_handle=None,
        sandbox_provider=None,
        sandbox_session_key=None,
    )


def _make_chain(chunks):
    """Build a fake agent_chain whose astream() yields the given (mode, chunk)
    tuples, scripted ahead of time."""

    async def _gen():
        for item in chunks:
            yield item

    chain = MagicMock()
    chain.astream.return_value = _gen()
    return chain


def _make_raising_chain(exc: BaseException):
    """Build a fake agent_chain whose astream() raises ``exc`` before yielding."""

    async def _gen():
        raise exc
        yield None  # pragma: no cover - makes this an async generator

    chain = MagicMock()
    chain.astream.return_value = _gen()
    return chain


class _StreamHarness:
    """Collects the SSE strings yielded by one ``stream_agent_chat`` call plus
    the kwargs passed to the (patched) ``record_agent_execution`` spy."""

    def __init__(self):
        self.recorded_kwargs: dict = {}

    def recorder(self, **kwargs):
        self.recorded_kwargs.update(kwargs)


async def _run(
    *,
    ctx,
    create_agent_mock,
    finalize_return=None,
    extra_patches=None,
):
    """Drive ``AgentStreamingService.stream_agent_chat`` to completion and
    return (list_of_sse_strings, harness)."""
    from services.agent_streaming_service import AgentStreamingService

    execution_service = MagicMock()
    execution_service._prepare_turn = AsyncMock(return_value=ctx)
    execution_service._finalize_turn = AsyncMock(
        return_value=finalize_return
        or {
            "parsed_response": "hello world",
            "effective_conv_id": 297,
            "files_data": [],
        }
    )
    execution_service._begin_sandbox_turn = MagicMock(return_value=False)
    execution_service._end_sandbox_turn = MagicMock()

    harness = _StreamHarness()

    service = AgentStreamingService()
    service.execution_service = execution_service
    db = MagicMock()

    patches = [
        patch("services.agent_streaming_service.create_agent", create_agent_mock),
        patch(
            "services.agent_streaming_service.prepare_agent_config",
            return_value={"configurable": {}},
        ),
        patch(
            "services.agent_streaming_service.build_human_message",
            return_value=SimpleNamespace(content="hello"),
        ),
        patch(
            "services.agent_streaming_service.resolve_langsmith_settings",
            return_value=None,
        ),
        patch(
            "services.agent_streaming_service.record_agent_execution",
            side_effect=harness.recorder,
        ),
    ]
    if extra_patches:
        patches.extend(extra_patches)

    from contextlib import ExitStack

    with ExitStack() as stack:
        for p in patches:
            stack.enter_context(p)

        events = [
            event
            async for event in service.stream_agent_chat(
                agent_id=1,
                message="hello",
                file_references=[],
                user_context={"user_id": "u1"},
                conversation_id=297,
                db=db,
            )
        ]

    return events, harness


# ---------------------------------------------------------------------------
# Golden scenarios
# ---------------------------------------------------------------------------


class TestAgentStreamingGolden:
    """Pins the exact SSE byte sequence of ``stream_agent_chat`` for each
    documented scenario (plan step_004, scenarios 1-8)."""

    @pytest.mark.asyncio
    async def test_plain_tokens(self):
        chain = _make_chain(
            [
                ("messages", (AIMessageChunk(content="Hello"), {})),
                ("messages", (AIMessageChunk(content=" world"), {})),
            ]
        )
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(ctx=_make_ctx(), create_agent_mock=create_agent)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "token", "data": {"content": "Hello"}}\n\n',
            'data: {"type": "token", "data": {"content": " world"}}\n\n',
            'data: {"type": "done", "data": {"response": "hello world", "conversation_id": 297, "files": []}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "SUCCESS"
        assert harness.recorded_kwargs["error_code"] is None
        assert harness.recorded_kwargs["time_to_first_token_ms"] is not None

    @pytest.mark.asyncio
    async def test_tool_start_and_tool_end(self):
        ai_msg = AIMessage(
            content="",
            tool_calls=[{"name": "web_search", "id": "call_1", "args": {"q": "x"}}],
        )
        tool_msg = ToolMessage(
            content="result-content", tool_call_id="call_1", name="web_search"
        )
        chain = _make_chain(
            [
                ("updates", {"agent": {"messages": [ai_msg]}}),
                ("updates", {"tools": {"messages": [tool_msg]}}),
            ]
        )
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(ctx=_make_ctx(), create_agent_mock=create_agent)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "tool_start", "data": {"tool_name": "web_search", "tool_call_id": "call_1", "args": {"q": "x"}, "tool_input": "{\\"q\\": \\"x\\"}"}}\n\n',
            'data: {"type": "thinking", "data": {"message": "Searching the web...", "tool_name": "web_search"}}\n\n',
            'data: {"type": "tool_end", "data": {"tool_name": "web_search", "tool_call_id": "call_1", "tool_output": "result-content"}}\n\n',
            'data: {"type": "done", "data": {"response": "hello world", "conversation_id": 297, "files": []}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "SUCCESS"
        # No "token" events were emitted in this scenario, so no first-token
        # timestamp was ever captured.
        assert harness.recorded_kwargs["time_to_first_token_ms"] is None

    @pytest.mark.asyncio
    async def test_parallel_tool_calls_preserve_order(self):
        """Two tool_calls on a single AIMessage must each get their own
        tool_start/thinking pair, in call order, followed by their tool_end
        events in the order the ToolMessages arrive."""
        ai_msg = AIMessage(
            content="",
            tool_calls=[
                {"name": "web_search", "id": "call_1", "args": {"q": "x"}},
                {"name": "python_repl", "id": "call_2", "args": {"code": "1+1"}},
            ],
        )
        tool_msg_1 = ToolMessage(
            content="search-result", tool_call_id="call_1", name="web_search"
        )
        tool_msg_2 = ToolMessage(content="2", tool_call_id="call_2", name="python_repl")
        chain = _make_chain(
            [
                ("updates", {"agent": {"messages": [ai_msg]}}),
                ("updates", {"tools": {"messages": [tool_msg_1, tool_msg_2]}}),
            ]
        )
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(ctx=_make_ctx(), create_agent_mock=create_agent)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "tool_start", "data": {"tool_name": "web_search", "tool_call_id": "call_1", "args": {"q": "x"}, "tool_input": "{\\"q\\": \\"x\\"}"}}\n\n',
            'data: {"type": "thinking", "data": {"message": "Searching the web...", "tool_name": "web_search"}}\n\n',
            'data: {"type": "tool_start", "data": {"tool_name": "python_repl", "tool_call_id": "call_2", "args": {"code": "1+1"}, "tool_input": "{\\"code\\": \\"1+1\\"}"}}\n\n',
            'data: {"type": "thinking", "data": {"message": "Running code...", "tool_name": "python_repl"}}\n\n',
            'data: {"type": "tool_end", "data": {"tool_name": "web_search", "tool_call_id": "call_1", "tool_output": "search-result"}}\n\n',
            'data: {"type": "tool_end", "data": {"tool_name": "python_repl", "tool_call_id": "call_2", "tool_output": "2"}}\n\n',
            'data: {"type": "done", "data": {"response": "hello world", "conversation_id": 297, "files": []}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "SUCCESS"

    @pytest.mark.asyncio
    async def test_custom_mode_code_output_event(self):
        """A ``custom`` stream-mode chunk shaped as a code_output event
        (sandbox/code-interpreter stdout line) must pass its stream/line and
        optional tool_name/parent_tool_name/subagent_name/subagent_id fields
        through verbatim (tools/streaming_utils.py::_map_custom_chunk)."""
        chain = _make_chain(
            [
                (
                    "custom",
                    {
                        "type": "code_output",
                        "stream": "stdout",
                        "line": "hello\n",
                        "tool_name": "python_repl",
                        "parent_tool_name": "agent_tool",
                        "subagent_name": "sub1",
                        "subagent_id": "sid1",
                    },
                ),
            ]
        )
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(ctx=_make_ctx(), create_agent_mock=create_agent)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "code_output", "data": {"line": "hello\\n", "stream": "stdout", "tool_name": "python_repl", "parent_tool_name": "agent_tool", "subagent_name": "sub1", "subagent_id": "sid1"}}\n\n',
            'data: {"type": "done", "data": {"response": "hello world", "conversation_id": 297, "files": []}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "SUCCESS"

    @pytest.mark.asyncio
    async def test_custom_mode_tool_start_tool_end_thinking_passthrough(self):
        """``custom`` chunks already shaped like {"type": "tool_start"|"tool_end"|
        "thinking", "data": {...}} are forwarded as-is (passthrough branch of
        _map_custom_chunk)."""
        chain = _make_chain(
            [
                (
                    "custom",
                    {"type": "tool_start", "data": {"tool_name": "custom_tool", "tool_call_id": "c1"}},
                ),
                (
                    "custom",
                    {
                        "type": "tool_end",
                        "data": {
                            "tool_name": "custom_tool",
                            "tool_call_id": "c1",
                            "tool_output": "ok",
                        },
                    },
                ),
                ("custom", {"type": "thinking", "data": {"message": "Custom thinking"}}),
            ]
        )
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(ctx=_make_ctx(), create_agent_mock=create_agent)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "tool_start", "data": {"tool_name": "custom_tool", "tool_call_id": "c1"}}\n\n',
            'data: {"type": "tool_end", "data": {"tool_name": "custom_tool", "tool_call_id": "c1", "tool_output": "ok"}}\n\n',
            'data: {"type": "thinking", "data": {"message": "Custom thinking"}}\n\n',
            'data: {"type": "done", "data": {"response": "hello world", "conversation_id": 297, "files": []}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "SUCCESS"

    @pytest.mark.asyncio
    async def test_custom_mode_generic_string_and_dict_fallback_to_thinking(self):
        """A plain string or an arbitrary dict with no recognised "type" key
        falls back to a generic ``thinking`` event (the final branch of
        _map_custom_chunk)."""
        chain = _make_chain(
            [
                ("custom", "Plain string status"),
                ("custom", {"foo": "bar"}),
            ]
        )
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(ctx=_make_ctx(), create_agent_mock=create_agent)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "thinking", "data": {"message": "Plain string status"}}\n\n',
            'data: {"type": "thinking", "data": {"foo": "bar"}}\n\n',
            'data: {"type": "done", "data": {"response": "hello world", "conversation_id": 297, "files": []}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "SUCCESS"

    @pytest.mark.asyncio
    async def test_structured_response_via_updates_chunk(self):
        chain = _make_chain(
            [
                ("messages", (AIMessageChunk(content="partial"), {})),
                ("updates", {"model": {"structured_response": {"answer": 42}}}),
            ]
        )
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(
            ctx=_make_ctx(),
            create_agent_mock=create_agent,
            finalize_return={
                "parsed_response": {"answer": 42},
                "effective_conv_id": 297,
                "files_data": [],
            },
        )

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "token", "data": {"content": "partial"}}\n\n',
            'data: {"type": "done", "data": {"response": {"answer": 42}, "conversation_id": 297, "files": []}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "SUCCESS"

    @pytest.mark.asyncio
    async def test_finalize_turn_returns_files_data(self):
        chain = _make_chain([("messages", (AIMessageChunk(content="hi"), {}))])
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(
            ctx=_make_ctx(),
            create_agent_mock=create_agent,
            finalize_return={
                "parsed_response": "hi",
                "effective_conv_id": 297,
                "files_data": [{"filename": "out.txt", "file_id": 5}],
            },
        )

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "token", "data": {"content": "hi"}}\n\n',
            'data: {"type": "done", "data": {"response": "hi", "conversation_id": 297, "files": [{"filename": "out.txt", "file_id": 5}]}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "SUCCESS"

    @pytest.mark.asyncio
    async def test_exception_mid_stream_yields_generic_error(self):
        async def _gen():
            yield ("messages", (AIMessageChunk(content="partial"), {}))
            raise RuntimeError("boom")

        chain = MagicMock()
        chain.astream.return_value = _gen()
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(ctx=_make_ctx(), create_agent_mock=create_agent)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "token", "data": {"content": "partial"}}\n\n',
            'data: {"type": "error", "data": {"message": "Agent execution failed"}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "ERROR"
        assert harness.recorded_kwargs["error_code"] == "RuntimeError"
        assert harness.recorded_kwargs["error_message"] == "boom"
        assert harness.recorded_kwargs["time_to_first_token_ms"] is not None

    @pytest.mark.asyncio
    async def test_psycopg_operational_error_yields_connection_error(self):
        async def _gen():
            yield ("messages", (AIMessageChunk(content="partial"), {}))
            raise psycopg.OperationalError("conn lost")

        chain = MagicMock()
        chain.astream.return_value = _gen()
        create_agent = AsyncMock(return_value=(chain, None))

        events, harness = await _run(ctx=_make_ctx(), create_agent_mock=create_agent)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
            'data: {"type": "token", "data": {"content": "partial"}}\n\n',
            'data: {"type": "error", "data": {"message": "Connection error, please retry."}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "ERROR"
        assert harness.recorded_kwargs["error_code"] == "OperationalError"
        assert harness.recorded_kwargs["error_message"] == "Connection error, please retry."

    @pytest.mark.asyncio
    async def test_missing_tool_output_retry_with_rollback_checkpoint(self):
        ctx = _make_ctx(
            has_memory=True,
            conversation=SimpleNamespace(session_id="conv_1_297"),
            session_id_for_cache="297",
        )

        first_chain = _make_raising_chain(
            RuntimeError(
                "Error code: 400 - No tool output found for function call call_stale"
            )
        )
        second_chain = _make_chain(
            [("messages", (AIMessageChunk(content="recovered"), {}))]
        )
        create_agent = AsyncMock(
            side_effect=[(first_chain, None), (second_chain, None)]
        )

        extra_patches = [
            patch(
                "services.agent_streaming_service.is_missing_tool_output_error",
                side_effect=lambda exc: "No tool output found" in str(exc),
            ),
            patch(
                "services.agent_streaming_service.CheckpointerCacheService"
                ".get_rollback_checkpoint_id",
                new=AsyncMock(return_value="01ARZ3NDEKTSV4RRFFQ69G5FAV"),
            ),
        ]

        events, harness = await _run(
            ctx=ctx, create_agent_mock=create_agent, extra_patches=extra_patches
        )

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": "conv_1_297", "agent_id": 1, "agent_name": "TestAgent", "has_memory": true}}\n\n',
            'data: {"type": "token", "data": {"content": "recovered"}}\n\n',
            'data: {"type": "done", "data": {"response": "hello world", "conversation_id": 297, "files": []}}\n\n',
        ]
        assert create_agent.call_count == 2
        assert (
            second_chain.astream.call_args.kwargs["config"]["configurable"][
                "checkpoint_id"
            ]
            == "01ARZ3NDEKTSV4RRFFQ69G5FAV"
        )
        assert harness.recorded_kwargs["status"] == "SUCCESS"

    @pytest.mark.asyncio
    async def test_missing_tool_output_retry_without_rollback_checkpoint(self):
        ctx = _make_ctx(
            has_memory=True,
            conversation=SimpleNamespace(session_id="conv_1_297"),
            session_id_for_cache="297",
        )

        first_chain = _make_raising_chain(
            RuntimeError(
                "Error code: 400 - No tool output found for function call call_stale"
            )
        )
        create_agent = AsyncMock(return_value=(first_chain, None))

        extra_patches = [
            patch(
                "services.agent_streaming_service.is_missing_tool_output_error",
                side_effect=lambda exc: "No tool output found" in str(exc),
            ),
            patch(
                "services.agent_streaming_service.CheckpointerCacheService"
                ".get_rollback_checkpoint_id",
                new=AsyncMock(return_value=None),
            ),
        ]

        events, harness = await _run(
            ctx=ctx, create_agent_mock=create_agent, extra_patches=extra_patches
        )

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": "conv_1_297", "agent_id": 1, "agent_name": "TestAgent", "has_memory": true}}\n\n',
            'data: {"type": "error", "data": {"message": "Your last message could not be completed. Please resend it."}}\n\n',
        ]
        assert create_agent.call_count == 1
        assert harness.recorded_kwargs["status"] == "ERROR"
        assert harness.recorded_kwargs["error_code"] == "RuntimeError"
        assert (
            harness.recorded_kwargs["error_message"]
            == "Error code: 400 - No tool output found for function call call_stale"
        )

    @pytest.mark.asyncio
    async def test_consumer_aclose_mid_stream_records_cancelled(self):
        async def _gen():
            yield ("messages", (AIMessageChunk(content="partial"), {}))
            await asyncio.sleep(10)
            yield ("messages", (AIMessageChunk(content="more"), {}))  # pragma: no cover

        chain = MagicMock()
        chain.astream.return_value = _gen()
        create_agent = AsyncMock(return_value=(chain, None))

        from services.agent_streaming_service import AgentStreamingService

        execution_service = MagicMock()
        execution_service._prepare_turn = AsyncMock(return_value=_make_ctx())
        execution_service._finalize_turn = AsyncMock()
        execution_service._begin_sandbox_turn = MagicMock(return_value=False)
        execution_service._end_sandbox_turn = MagicMock()

        harness = _StreamHarness()
        service = AgentStreamingService()
        service.execution_service = execution_service
        db = MagicMock()

        from contextlib import ExitStack

        events = []
        with ExitStack() as stack:
            stack.enter_context(
                patch("services.agent_streaming_service.create_agent", create_agent)
            )
            stack.enter_context(
                patch(
                    "services.agent_streaming_service.prepare_agent_config",
                    return_value={"configurable": {}},
                )
            )
            stack.enter_context(
                patch(
                    "services.agent_streaming_service.build_human_message",
                    return_value=SimpleNamespace(content="hello"),
                )
            )
            stack.enter_context(
                patch(
                    "services.agent_streaming_service.resolve_langsmith_settings",
                    return_value=None,
                )
            )
            stack.enter_context(
                patch(
                    "services.agent_streaming_service.record_agent_execution",
                    side_effect=harness.recorder,
                )
            )

            gen = service.stream_agent_chat(
                agent_id=1,
                message="hello",
                file_references=[],
                user_context={"user_id": "u1"},
                conversation_id=297,
                db=db,
            )
            events.append(await gen.__anext__())
            # Bound the wait so a regression that swallows CancelledError/GeneratorExit
            # (instead of re-raising, per AD-6 / the streaming seam contract) fails
            # fast with a TimeoutError instead of hanging the whole test run.
            await asyncio.wait_for(gen.aclose(), timeout=1)

        assert events == [
            'data: {"type": "metadata", "data": {"conversation_id": 297, "session_id": null, "agent_id": 1, "agent_name": "TestAgent", "has_memory": false}}\n\n',
        ]
        assert harness.recorded_kwargs["status"] == "ERROR"
        assert harness.recorded_kwargs["error_code"] == "Cancelled"
        assert harness.recorded_kwargs["error_message"] == "Stream cancelled"
        execution_service._finalize_turn.assert_not_awaited()
